### ISSUE TITLE
Test Failing only for delay scenario

### ISSUE THREAD

**Issue by Premraj-Murugaraj** [dilipsundarraj1/wiremock-for-java-developers#2]
Hi Dilip,
Wiremock test for retrieveAllMovies_fixedDelay() and retrieveAllMovies_RandomDelay() is alone failing due to below errors. could you please help.

java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.jetty.server.Server.doStop(Server.java:490)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.stop(JettyHttpServer.java:243)
	at com.github.tomakehurst.wiremock.WireMockServer.stop(WireMockServer.java:147)
	at com.github.jenspiegsa.wiremockextension.WireMockExtension.stopServer(WireMockExtension.java:172)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.jenspiegsa.wiremockextension.WireMockExtension.afterEach(WireMockExtension.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$12(TestMethodTestDescriptor.java:260)

**Comment by Premraj1212** [comment]
Issue resolved it can be closed.

**Comment by Premraj-Murugaraj** [comment]
Issue resolved this can be closed.
